services:
  django-backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  nextjs-frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - django-backend
